---
# From ansible-galaxy (a release tag)
- src: "adrianjuhl.maven"
  version: "0.4.0"

# From a branch from the github repo
#- src: "https://github.com/adrianjuhl/ansible-role-maven"
#  scm: "git"
#  version: "0.4.0-develop-WIP-2"
#  name: "adrianjuhl.maven"
