---
# tasks file for adrianjuhl.maven

- name: Create maven install directory.
  file:
    dest: "{{ adrianjuhl__maven__maven_install_directory }}"
    state: directory
  become: true

- name: Create download directory
  file:
    state: directory
    mode: "u=rwx,go=rx"
    dest: "{{ adrianjuhl__maven__maven_download_directory }}"

- name: Download Maven
  get_url:
    url: "{{ adrianjuhl__maven__maven_source_directory }}/{{ adrianjuhl__maven__maven_filename }}"
    dest: "{{ adrianjuhl__maven__maven_download_directory }}/{{ adrianjuhl__maven__maven_filename }}"
    checksum: "sha512:{{ adrianjuhl__maven__maven_file_checksums[adrianjuhl__maven__maven_version] }}"
    force: no
#    use_proxy: '{{ maven_use_proxy }}'
#    validate_certs: '{{ maven_validate_certs }}'
#    timeout: '{{ maven_download_timeout }}'
#    mode: 'u=rw,go=r'

- name: Unarchive maven.
  unarchive:
    src: "{{ adrianjuhl__maven__maven_download_directory }}/{{ adrianjuhl__maven__maven_filename }}"
    dest: "{{ adrianjuhl__maven__maven_install_directory }}"
    copy: false
  become: true

- name: Install maven alternative
  community.general.alternatives:
    name: mvn
    path: "{{ adrianjuhl__maven__maven_install_directory }}/apache-maven-{{ adrianjuhl__maven__maven_version }}/bin/mvn"
    link: /usr/bin/mvn
  become: true

