---
# tasks file for adrianjuhl.maven

- name: "Create download directory"
  ansible.builtin.file:
    dest: "{{ adrianjuhl__maven__maven_download_directory }}"
    state: "directory"
    mode: "u=rwx,go=rx"

- name: "Download Maven"
  ansible.builtin.get_url:
    url: "{{ adrianjuhl__maven__maven_source_url_directory }}/{{ adrianjuhl__maven__maven_archive_file_name }}"
    dest: "{{ adrianjuhl__maven__maven_download_directory }}"
    checksum: "{{ adrianjuhl__maven__maven_archive_file_checksum }}"
    force: true
    mode: "u=rw,go=r"

- name: "Create maven install directory"
  ansible.builtin.file:
    dest: "{{ adrianjuhl__maven__maven_install_directory }}"
    state: "directory"
    mode: "u=rwx,go=rx"

- name: "Unarchive maven"
  ansible.builtin.unarchive:
    src: "{{ adrianjuhl__maven__maven_download_directory }}/{{ adrianjuhl__maven__maven_archive_file_name }}"
    dest: "{{ adrianjuhl__maven__maven_install_directory }}"
    copy: false

- name: "Configure maven alternative"
  community.general.alternatives:
    name: "mvn"
    path: "{{ adrianjuhl__maven__maven_install_directory }}/apache-maven-{{ adrianjuhl__maven__maven_version }}/bin/mvn"
    link: "/usr/bin/mvn"
    priority: "{{ adrianjuhl__maven__maven_alternatives_priority }}"
    state: "{{ adrianjuhl__maven__maven_alternatives_state }}"
