---
# tasks file for adrianjuhl.maven

- name: Example print message
  ansible.builtin.debug:
    msg: "hello from role adrianjuhl.maven - variable adrianjuhl__maven__file_checksum has the value: {{ adrianjuhl__maven__file_checksum }}"
- name: Example print message
  ansible.builtin.debug:
    msg: "hello from role adrianjuhl.maven - variable adrianjuhl__maven__filename has the value: {{ adrianjuhl__maven__filename }}"

- name: Create download directory
  file:
    dest: "{{ adrianjuhl__maven__download_directory }}/maven/maven-{{ adrianjuhl__maven__version_major }}/{{ adrianjuhl__maven__version }}"
    state: directory
    mode: "u=rwx,go=rx"

- name: Download Maven
  get_url:
    url: "{{ adrianjuhl__maven__source_directory }}/{{ adrianjuhl__maven__filename }}"
    dest: "{{ adrianjuhl__maven__download_directory }}/maven/maven-{{ adrianjuhl__maven__version_major }}/{{ adrianjuhl__maven__version }}"
    checksum: "{{ adrianjuhl__maven__file_checksum }}"
    force: no
    mode: "u=rw,go=r"

- name: Create maven install directory.
  file:
    dest: "{{ adrianjuhl__maven__install_directory }}"
    state: directory
  become: true

- name: Unarchive maven.
  unarchive:
    src: "{{ adrianjuhl__maven__download_directory }}/maven/maven-{{ adrianjuhl__maven__version_major }}/{{ adrianjuhl__maven__version }}"
    dest: "{{ adrianjuhl__maven__install_directory }}"
    copy: false
  become: true

- name: Install maven alternative
  community.general.alternatives:
    name: mvn
    path: "{{ adrianjuhl__maven__install_directory }}/apache-maven-{{ adrianjuhl__maven__version }}/bin/mvn"
    link: /usr/bin/mvn
    priority: "{{ adrianjuhl__maven__alternatives_priority }}"
    state: "{{ adrianjuhl__maven__alternatives_state }}"
  become: true

