---
- name: Install maven
  hosts: localhost
  tasks:
    - name: Install maven
      include_role:
        name: adrianjuhl.maven
        apply:
          become: "{{ local_playbook__install_maven__requires_become }}"
